resources:
  repositories:
  - repository: devops  # arbitrary identifier (A-Z, a-z, 0-9, and underscore)
    type: github
    name: MobisysGmbh/devops-templates  # repository name (format depends on `type`)
    endpoint: MobisysGmbH  # name of the service connection to use (for types that aren't Azure Repos)
    ref: refs/heads/v5-add # defaults to refs/heads/main if ref is not set

parameters:
  - name: dryRun
    type: boolean
    displayName: Only do test run - No real publishing!
    default: true

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/publish-to-npmjs-pipeline.yml@devops
  parameters:
    dryRun: ${{ parameters.dryRun }}
    publishingBranch: 'refs/heads/main'
    applicationRootPath: $(Build.SourcesDirectory)
    vmImage: 'ubuntu-latest'